#端口
server:
  port: 8082
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
spring:
  profiles:
    active: dev
  #项目名
  application:
    name: dazi-finder
  #session配置1天
  session:
    timeout: 86400
    store-type: redis
  #数据库配置
  datasource:
    driver-class-name: ${df.datasource.driver-class-name}
    url: jdbc:mysql://${df.datasource.host}:${df.datasource.port}/${df.datasource.database}
    username: ${df.datasource.username}
    password: ${df.datasource.password}
  # Redis 配置
  redis:
    host: ${df.redis.host}
    port: ${df.redis.port}
    password: ${df.redis.password}
    database: ${df.redis.database}
  main:
    banner-mode: off
mybatis-plus:
  configuration:
    #关闭驼峰映射
    map-underscore-to-camel-case: false
    #mybatis日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
df:
  #阿里云OSS
  alioss:
    endpoint: ${df.alioss.endpoint}
    bucket-name: ${df.alioss.bucket-name}
    folder-name: ${df.alioss.folder-name}
knife4j:
  enable: true
  openapi:
    title: 找搭子API文档
    description: 接口文档
    version: v1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.alan.controller